test_subcmds_sync.py: fix for py36 and py37
tests/test_subcmds_sync.py::LocalSyncState::test_prune_removed_projects was
failing in Python 3.6 and 3.7 due to topdir not being set with the following
error message:
    TypeError: expected str, bytes or os.PathLike object, not MagicMock

Top dir is accessed from within PruneRemovedProjects().

Test: tox with Python 3.6 to 3.11
Change-Id: I7ba5144df0a0126c01776384e2178136c3510091