superproject: Change bug reporting url to go/repo-bug for missing commit ids.
Tested the code with the following commands.

$ ./run_tests -v

error: please file a bug using go/repo-bug to report missing commit_ids for: ['art', ...
Bug: [google internal] b/186220520.
Change-Id: If075553813a0339ccf46ab3acaa38041fff552ca