Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> i posted https://gerrit-review.googlesource.com/c/git-repo/+/248972 to handle env issues.  can you check that works for you instead ?

It doesn't work because of platform_utils_win32.py incompatibility with Python 3.8.1. But together with my change of the platform_utils_win32.py from this pull request it works.

Traceback (most recent call last):
  File "D:\develop\git-repo\main.py", line 541, in <module>
    _Main(sys.argv[1:])
  File "D:\develop\git-repo\main.py", line 516, in _Main
    result = run()
  File "D:\develop\git-repo\main.py", line 509, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "D:\develop\git-repo\main.py", line 212, in _Run
    result = cmd.Execute(copts, cargs)
  File "D:\develop\git-repo\subcmds\init.py", line 451, in Execute
    self._SyncManifest(opt)
  File "D:\develop\git-repo\subcmds\init.py", line 196, in _SyncManifest
    m._InitGitDir(mirror_git=mirrored_manifest_git)
  File "D:\develop\git-repo\project.py", line 2574, in _InitGitDir
    self._UpdateHooks()
  File "D:\develop\git-repo\project.py", line 2595, in _UpdateHooks
    self._InitHooks()
  File "D:\develop\git-repo\project.py", line 2598, in _InitHooks
    hooks = platform_utils.realpath(self._gitdir_path('hooks'))
  File "D:\develop\git-repo\project.py", line 2796, in _gitdir_path
    return platform_utils.realpath(os.path.join(self.gitdir, path))
  File "D:\develop\git-repo\platform_utils.py", line 402, in realpath
    if islink(current_path):
  File "D:\develop\git-repo\platform_utils.py", line 371, in islink
    import platform_utils_win32
  File "D:\develop\git-repo\platform_utils_win32.py", line 21, in <module>
    from ctypes.wintypes import BOOL, BOOLEAN, LPCWSTR, DWORD, HANDLE, POINTER, c_ubyte
ImportError: cannot import name 'POINTER' from 'ctypes.wintypes' (C:\Program Files\Python38\lib\ctypes\wintypes.py)

Patch-set: 1