Return support for python 2.7
After 7f7acfe9fd93cfd4a697f2bc851d1b8182f6336e commit python 2.7 failed
to parse hooks.py file with the following error:

> Traceback (most recent call last):
>   File ".repo/repo/main.py", line 56, in <module>
>     from subcmds.version import Version
>   File ".repo/repo/subcmds/__init__.py", line 38, in <module>
>     ['%s' % name])
>   File ".repo/repo/subcmds/upload.py", line 27, in <module>
>     from hooks import RepoHook
>   File ".repo/repo/hooks.py", line 472
>     file=sys.stderr)
>         ^
> SyntaxError: invalid syntax

Add required 'from __future__ import print_function' to solve this issue.

Change-Id: I7ef0f7302d3ca4d66a616655a2946c11e560728d