sync: Don't raise exception in _FetchOne & _CheckOne, print error.GitError.
This fixes the exceptions from /usr/lib/python3.8/multiprocessing/pool.py
exiting the repo sync.

Tested the code with the following commands and verified repo sync
continues after fetch error because of an invalid SHA1.

$ ./run_tests -v

$ python3 ~/work/repo/git-repo/repo sync -m manifest_P21623846.xml -j32
...
error: Cannot fetch platform/vendor/google_devices/gs101/prebuilts (GitError: platform/vendor/google_devices/gs101/prebuilts update-ref: fatal: 18d4bc4f27aab25fe55985dace63b6323b899fe4^0: not a valid SHA1
)
Fetching: 21% (438/2061) platform/external/mkshInvalid clone.bundle file; ignoring.
Fetching: 84% (1736/2061) platform/vendor/qcom/sm7250/proprietary/mm-videoInvalid clone.bundle file; ignoring.
....

Bug: https://crbug.com/gerrit/14392
Change-Id: I8922ad6c07c733125419f5698b0f7e32d70c7905