Revert "Fix shallow clones when upstream attribute is present"
This reverts commit d9cc0a15265299b6dcfc1d65f192fd14cfb17b02.

Reason for revert: AttributeError: 'Project' object has no attribute 'use_superproject'

Bug: b/427093249
Change-Id: I57b285ab21f58b040e68ec14b85425f43f0abcca