Update patch set 1
Patch Set 1:

If you use python3 to sync, then go back to python2, the resultant is an error originating from subcmds/sync.py:788

ValueError: unsupported pickle protocol: 3

To solve this, .repo/.repopickle_fetchtimes needs to be removed

A check should be to ensure the file is of the correct format for the corresponding version of python

Patch-set: 1
Label: Verified=0