Fix urllib.parse(urlparse) handling
Revert "Fix "'module' object is not callable" error"

* The urlparse module is renamed to urllib.parse in Python 3.
* This commit fixes the code to use "urllib.parse.urlparse"
  instead of creating a new module urlib and setting
  urlib.parse to urlparse.urlparse.
* Fixes an AttributeError:
  'function' object has no attribute 'uses_relative'

This reverts commit cd51f17c643370e6199216462c1be36f04d57291.

Change-Id: I48490b20ecd19cf5a6edd835506ea5a467d556ac