Fix fail in test_repo_trace if trace is disabled
If env has REPO_TRACE 0, then this test produces:
FileNotFoundError: No such file or directory: TRACE_FILE_from_test'
because it assumes trace is always enabled.

Improve by enabling trace for just this test if it
was disabled, without impacting the env variable.

Change-Id: I2bb4632eb45ee529fc1785833e0bafd9c36f0875