Improve error message on base check fail
Previous error had a scent of alien blob to it
due to dumping the list in a single long line, so
improve print for human readability.

Example of new fail:

detected revision base mismatch
remove-project path build/make:
 fccb6b3e884b4b964e795f5f8865f6bbb4722b5a vs 6e9a0c16f20d1cfcf08b8b9cb42301b6c9712862
remove-project path build/soong:
 16b3c9ca0679bb376966866afb849322c8aec79f vs b7490575c16b87d861a532b03bd1b2d076b6fa0b
extend-project name platform/system/sepolicy:
 c2652856e9f0e0433d78cfb481efe392d6f5dbc4 vs cf9a73f92f503ffc4bd3e726164babfb40a9fcaf
error: in `manifest`: rebase patches and update base revs

Change-Id: I8d741e11c69ef9e4f8cf09e32aa0868b6daa5acd