Update patch set 2
Patch Set 2:

Brian-

Can you clarify what you mean by 'tracking info goes to hell'? I simulated the situation where the remote branch is deleted and then I run repo sync. It gives an appropriate error, but the tracking info in .git/config is not changed. i.e.:

 Pruning aosp
 URL: /tmp/mirror/platform/packages/apps/Mms
  * [pruned] aosp/master
  refs/remotes/m/master has become dangling!
 error: revision master in platform/packages/apps/Mms not found
 $ cat .git/config
 ...
 [branch "mybr"]
 	remote = aosp
 	merge = master

So, is that "merge=master" what you mean by "goes to hell"? I'm not sure there's anything better it could be changed to. Maybe the entire "mybr" stanza could be deleted. What do you think?

Patch-set: 2