git_superproject: make _Init return early if git dir exists
Instead of unconditionally doing `git init --bar $DIR`, return early if
$DIR exists.

Otherwise, init can fail with errors like:

error: could not lock config file /.repo/exp-superproject/b438af8-superproject.git/config: File exists

Bug: 434924251
Change-Id: Ie4e55bbf921c77dd0da8c7f92458bcb51cdcf0e0