superproject: require git version 2.28.0 or higher.
Tested the code with the following commands.

$ repo init --use-superproject -u https://android.googlesource.com/platform/manifest
$ ./run_tests -v

Test for the version.
$ repo_dev init --use-superproject -u https://android.googlesource.com/platform/manifest
WARNING: --use-superproject is experimental and not for general use
superproject requires a git version 2.28 or later
error: git update of superproject failed

Bug: https://crbug.com/gerrit/14617
Bug: [google internal] b/189846687
Change-Id: I5cd4158ea29b3b3c8c81234f4e818165de346e63