Fetch all tags by default, make repo work robustly with rebased git repos.
Some projects practice rebase workflow model. This still can be done
in downstream users friendly manner by regular tagging, as tagged revisions
persist across rebases. However, in case of rebase, a tag may become
dangling, non-referenced from a (master or other active) branch. This
is not a problem for git clone, which fetches all tags by default. But
repo fetches only refs/heads/*, so using a revision which pretty exists
in the repository may end up with error with, like:

error.GitError: boot/u-boot-linaro-stable update-ref: error: Trying to write ref refs/remotes/m/linaro_android_2.3.3 with nonexistant object 9736a9332fcfe5fef1361a6d91740e160ad04bd5
fatal: Cannot update the ref 'refs/remotes/m/linaro_android_2.3.3'.

This is especially hitting when using manifests generated using
"repo manifest -r", like: you supplied downstream users a manifest which
should provide 100% reproducibility (by just using exact SHA1 revision
ids for each component); each repository still has all revisions referenced,
but some might have been rebased, and per above, repo starts to fail on sync.
So, just switch to git clone compatible behavior.

Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>
Change-Id: I418b0aef6472c56a4e2fe6800d0bd1acd4b0ec76