Update patch set 5
Patch Set 5:

> I just tested it and successfully used --depth and revision= to get
 > a specific revision with a truncated history.  Could you try it out
 > and see if it's not sufficient for your use?


Ok, I did some tests, and it still doesn't work for me. It fails either at the local part of the sync when fetching a tag, or at the network part when fetching a sha1 (or so it seems), because it doesn't find the wanted revision. A simple case is the following : 
repo init -u https://android.googlesource.com/platform/manifest -b refs/tags/android-4.3.1_r1 --depth=1
repo sync
which leads, after fetching every projects, to :
error: revision refs/tags/android-4.3.1_r1 in platform/abi/cpp not found


To go further, I also did several other tests with different configurations. I wanted to test
- Our corporate repo + server (ssh) vs google repo + googlesource.com (https)
- fetching a tag vs fetching a sha1
- using init --depth=1 vs using clone-depth="1" in manifest
For each test I used a manifest with only one project (to speed sync up a bit) arbitrarily chosen, and when using a sha1, I took one arbitrarily too.
I provide one such manifest at the end of this message 

I used several setups, mixing the above properties.
Results were either :
"error: revision refs/tags/android-4.3.1_r1 in platform/packages/apps/Gallery not found" when revision was a tag
or :
"GitError: platform/packages/apps/Gallery update-ref: fatal: b4f7ff9b6af58894d3c4a258ee4053592042bbc0^0: not a valid SHA1" when revision was a sha1.
I provide a full stack trace at the end too.

When I run gitk in .repo/projects/packages/apps/Gallery, I have only the top of each branch with the previous commit (which is what I believe to be the behavior with --depth=1).

This is the behavior we've been encountering and which led to the "archive" commits. So, did I miss something to properly use the depth option? How did you test it to work successfully?



One of the manifests used :
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote  name="aosp" fetch=".." review="https://android-review.googlesource.com/" />
  <default revision="refs/tags/android-4.3.1_r1" remote="aosp" sync-j="4" />

  <project path="packages/apps/Gallery" name="platform/packages/apps/Gallery" revision="b4f7ff9b6af58894d3c4a258ee4053592042bbc0" clone-depth="1"/>
</manifest>

The corresponding full stacktrace :
$ repo sync
Fetching project platform/packages/apps/Gallery
remote: Counting objects: 993, done
remote: Finding sources: 100% (993/993)
remote: Getting sizes: 100% (665/665)
remote: Compressing objects: 100% (1925292/1925292)
remote: Total 993 (delta 399), reused 861 (delta 299)
Receiving objects: 100% (993/993), 1.05 MiB, done.
Resolving deltas: 100% (412/412), done.
From https://android.googlesource.com/platform/packages/apps/Gallery
 * [new branch]      eclair-passion-release -> aosp/eclair-passion-release
 * [new branch]      eclair-release -> aosp/eclair-release
 * [new branch]      eclair-sholes-release -> aosp/eclair-sholes-release
 * [new branch]      eclair-sholes-release2 -> aosp/eclair-sholes-release2
 * [new branch]      froyo      -> aosp/froyo
 * [new branch]      froyo-release -> aosp/froyo-release
 * [new branch]      gingerbread -> aosp/gingerbread
 * [new branch]      gingerbread-mr4-release -> aosp/gingerbread-mr4-release
 * [new branch]      gingerbread-release -> aosp/gingerbread-release
 * [new branch]      ics-factoryrom-2-release -> aosp/ics-factoryrom-2-release
 * [new branch]      ics-mr0    -> aosp/ics-mr0
 * [new branch]      ics-mr0-release -> aosp/ics-mr0-release
 * [new branch]      ics-mr1    -> aosp/ics-mr1
 * [new branch]      ics-mr1-release -> aosp/ics-mr1-release
 * [new branch]      ics-plus-aosp -> aosp/ics-plus-aosp
 * [new branch]      idea133    -> aosp/idea133
 * [new branch]      jb-dev     -> aosp/jb-dev
 * [new branch]      jb-mr0-release -> aosp/jb-mr0-release
 * [new branch]      jb-mr1-dev -> aosp/jb-mr1-dev
 * [new branch]      jb-mr1-dev-plus-aosp -> aosp/jb-mr1-dev-plus-aosp
 * [new branch]      jb-mr1-release -> aosp/jb-mr1-release
 * [new branch]      jb-mr1.1-dev -> aosp/jb-mr1.1-dev
 * [new branch]      jb-mr1.1-dev-plus-aosp -> aosp/jb-mr1.1-dev-plus-aosp
 * [new branch]      jb-mr1.1-release -> aosp/jb-mr1.1-release
 * [new branch]      jb-mr2-dev -> aosp/jb-mr2-dev
 * [new branch]      jb-mr2-release -> aosp/jb-mr2-release
 * [new branch]      jb-mr2.0-release -> aosp/jb-mr2.0-release
 * [new branch]      jb-mr2.0.0-release -> aosp/jb-mr2.0.0-release
 * [new branch]      jb-release -> aosp/jb-release
 * [new branch]      kitkat-cts-dev -> aosp/kitkat-cts-dev
 * [new branch]      kitkat-dev -> aosp/kitkat-dev
 * [new branch]      kitkat-mr1-release -> aosp/kitkat-mr1-release
 * [new branch]      kitkat-release -> aosp/kitkat-release
 * [new branch]      master     -> aosp/master
 * [new branch]      tools_r20  -> aosp/tools_r20
 * [new branch]      tools_r21  -> aosp/tools_r21
 * [new branch]      tools_r22  -> aosp/tools_r22
 * [new branch]      tools_r22.2 -> aosp/tools_r22.2
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/campergue/workspace_build/test-mki2-6/.repo/repo/subcmds/sync.py", line 256, in _FetchHelper
    no_tags=opt.no_tags)
  File "/home/campergue/workspace_build/test-mki2-6/.repo/repo/project.py", line 1035, in Sync_NetworkHalf
    self._InitMRef()
  File "/home/campergue/workspace_build/test-mki2-6/.repo/repo/project.py", line 2005, in _InitMRef
    self._InitAnyMRef(R_M + self.manifest.branch)
  File "/home/campergue/workspace_build/test-mki2-6/.repo/repo/project.py", line 2017, in _InitAnyMRef
    self.bare_git.UpdateRef(ref, dst, message = msg, detach = True)
  File "/home/campergue/workspace_build/test-mki2-6/.repo/repo/project.py", line 2199, in UpdateRef
    self.update_ref(*cmdv)
  File "/home/campergue/workspace_build/test-mki2-6/.repo/repo/project.py", line 2274, in runner
    p.stderr))
GitError: platform/packages/apps/Gallery update-ref: fatal: b4f7ff9b6af58894d3c4a258ee4053592042bbc0^0: not a valid SHA1

Patch-set: 5